"""Orbit and attitude modes of the environment stage (``docs/etapas/environment.md``, ADR 0023).

Sections of ``EnvironmentParameters``, edited as a form with the ``x-`` JSON Schema extensions
listed in ``hestia_core.mission``. Every field is optional so a draft can be incomplete; the
validation reports what is missing or inconsistent and never produces values. SI units.
"""

import math
import re
from enum import StrEnum

from pydantic import BaseModel, Field
from pydantic.config import JsonDict

from hestia_core.forms import ProblemCode, Problems, capitalize, format_km, unit
from hestia_core.orbits import GEO_ALTITUDE_M, sso_inclination_rad, sso_max_altitude_m

MIN_ALTITUDE_M = 100_000.0
"""Lowest altitude accepted for an orbit (Kármán line)."""


class OrbitType(StrEnum):
    SSO = "sso"
    KEPLERIAN = "keplerian"
    """LEO/MEO: defined by its elements (also elliptical)."""
    GEO = "geo"


class Axis(StrEnum):
    PX = "+X"
    MX = "-X"
    PY = "+Y"
    MY = "-Y"
    PZ = "+Z"
    MZ = "-Z"


class Target(StrEnum):
    NADIR = "nadir"
    ZENITH = "zenith"
    SUN = "sun"
    VELOCITY = "velocity"
    ANTI_VELOCITY = "anti_velocity"
    ORBIT_NORMAL = "orbit_normal"
    ANTI_ORBIT_NORMAL = "anti_orbit_normal"


ORBIT_TYPE_LABELS: dict[str, str] = {"sso": "SSO", "keplerian": "LEO/MEO", "geo": "GEO"}
TARGET_LABELS: JsonDict = {
    "nadir": "Nadir",
    "zenith": "Cénit",
    "sun": "Sol",
    "velocity": "Velocidad",
    "anti_velocity": "Antivelocidad",
    "orbit_normal": "Normal a la órbita",
    "anti_orbit_normal": "Antinormal a la órbita",
}
_OPPOSITE_TARGETS = {
    frozenset({Target.NADIR, Target.ZENITH}),
    frozenset({Target.VELOCITY, Target.ANTI_VELOCITY}),
    frozenset({Target.ORBIT_NORMAL, Target.ANTI_ORBIT_NORMAL}),
}

_SSO_ONLY: JsonDict = {"x-show-if": {"type": ["sso"]}}
_KEPLERIAN_ONLY: JsonDict = {"x-show-if": {"type": ["keplerian"]}}


class Orbit(BaseModel):
    type: OrbitType | None = Field(
        default=OrbitType.SSO,
        title="Tipo de órbita",
        json_schema_extra={
            "x-enum-labels": dict(ORBIT_TYPE_LABELS),
            "x-default": OrbitType.SSO.value,
            "x-notes": {
                "sso": "En una SSO la inclinación la fija la altitud: se calcula y se ve en la "
                "vista previa.",
                "geo": "Altitud 35 786 km, circular y ecuatorial.",
            },
        },
    )
    altitude: float | None = Field(
        default=None,
        title="Altitud",
        description="Órbita circular.",
        json_schema_extra=unit("m", "km", _SSO_ONLY),
    )
    ltan: str | None = Field(
        default=None,
        title="Hora local del nodo ascendente",
        description="Hora local (solar media) del nodo ascendente, HH:MM.",
        json_schema_extra={"x-input": "time", **_SSO_ONLY},
    )
    perigee_altitude: float | None = Field(
        default=None,
        title="Altitud del perigeo",
        json_schema_extra=unit("m", "km", _KEPLERIAN_ONLY),
    )
    apogee_altitude: float | None = Field(
        default=None,
        title="Altitud del apogeo",
        description="Vacío: órbita circular (igual al perigeo).",
        json_schema_extra=unit("m", "km", {**_KEPLERIAN_ONLY, "x-placeholder": "vacío = circular"}),
    )
    inclination: float | None = Field(
        default=None,
        title="Inclinación",
        json_schema_extra=unit("rad", "°", _KEPLERIAN_ONLY),
    )


_TARGET_EXTRA: JsonDict = {"x-enum-labels": TARGET_LABELS, "x-column-title": "Dirección"}


class AttitudeMode(BaseModel):
    """Attitude from two body axis → direction pairs: the primary holds exactly, the secondary
    sets the rotation about the primary."""

    id: str | None = Field(
        default=None, description="Generated by the backend when applied. Immutable."
    )
    name: str | None = Field(default=None, title="Nombre")
    primary_axis: Axis | None = Field(default=None, title="Eje primario")
    primary_target: Target | None = Field(
        default=None, title="Dirección primaria", json_schema_extra=_TARGET_EXTRA
    )
    secondary_axis: Axis | None = Field(default=None, title="Eje secundario")
    secondary_target: Target | None = Field(
        default=None,
        title="Dirección secundaria",
        json_schema_extra=_TARGET_EXTRA,
    )


# ---------------------------------------------------------------- derived by type


def nominal_altitude_m(orbit: Orbit) -> float | None:
    """Altitude the environment treats as nominal: SSO altitude, LEO/MEO perigee, GEO."""
    if orbit.type is OrbitType.SSO:
        return orbit.altitude
    if orbit.type is OrbitType.KEPLERIAN:
        return orbit.perigee_altitude
    if orbit.type is OrbitType.GEO:
        return GEO_ALTITUDE_M
    return None


def nominal_inclination_rad(orbit: Orbit) -> float | None:
    """Inclination of the orbit: computed for SSO, entered for LEO/MEO, 0 in GEO."""
    if orbit.type is OrbitType.SSO:
        if orbit.altitude is None:
            return None
        try:
            return sso_inclination_rad(orbit.altitude)
        except ValueError:
            return None
    if orbit.type is OrbitType.KEPLERIAN:
        return orbit.inclination
    if orbit.type is OrbitType.GEO:
        return 0.0
    return None


# ---------------------------------------------------------------- validation

_TIME = re.compile(r"^([01]\d|2[0-3]):[0-5]\d$")

_ORBIT_FIELDS: dict[OrbitType, tuple[str, ...]] = {
    OrbitType.SSO: ("altitude", "ltan"),
    OrbitType.KEPLERIAN: ("perigee_altitude", "apogee_altitude", "inclination"),
    OrbitType.GEO: (),
}
_ORBIT_LABELS = {
    "altitude": "la altitud",
    "ltan": "la hora local del nodo ascendente",
    "perigee_altitude": "la altitud del perigeo",
    "apogee_altitude": "la altitud del apogeo",
    "inclination": "la inclinación",
}


def validate_orbit(p: Problems, orbit: Orbit, path: str = "orbit") -> None:
    """Required fields of the orbit type, only those, and their ranges."""
    if not p.required(f"{path}.type", orbit.type, "el tipo de órbita"):
        return
    assert orbit.type is not None
    allowed = _ORBIT_FIELDS[orbit.type]
    for name, label in _ORBIT_LABELS.items():
        if name not in allowed and getattr(orbit, name) is not None:
            p.add(
                f"{path}.{name}",
                ProblemCode.NOT_ALLOWED,
                f"{capitalize(label)} no corresponde a una órbita "
                f"{ORBIT_TYPE_LABELS[orbit.type.value]}: dejalo vacío.",
            )
    if orbit.type is OrbitType.SSO:
        _validate_sso(p, orbit, path)
    elif orbit.type is OrbitType.KEPLERIAN:
        _validate_keplerian(p, orbit, path)


def _validate_sso(p: Problems, orbit: Orbit, path: str) -> None:
    if p.required(f"{path}.altitude", orbit.altitude, "la altitud"):
        assert orbit.altitude is not None
        _min_altitude(p, f"{path}.altitude", orbit.altitude, "La altitud")
        max_altitude = sso_max_altitude_m()
        if orbit.altitude > max_altitude:
            p.add(
                f"{path}.altitude",
                ProblemCode.SSO_ALTITUDE,
                f"No hay órbitas heliosincrónicas por encima de {format_km(max_altitude)}.",
            )
    ltan = orbit.ltan
    if p.required(f"{path}.ltan", ltan, _ORBIT_LABELS["ltan"]) and not _TIME.match(ltan or ""):
        p.add(f"{path}.ltan", ProblemCode.FORMAT, "La hora local tiene que tener el formato HH:MM.")


def _validate_keplerian(p: Problems, orbit: Orbit, path: str) -> None:
    perigee = orbit.perigee_altitude
    if p.required(f"{path}.perigee_altitude", perigee, "la altitud del perigeo"):
        assert perigee is not None
        _min_altitude(p, f"{path}.perigee_altitude", perigee, "La altitud del perigeo")
    if orbit.apogee_altitude is not None:
        _min_altitude(p, f"{path}.apogee_altitude", orbit.apogee_altitude, "La altitud del apogeo")
        if perigee is not None and orbit.apogee_altitude < perigee:
            p.add(
                f"{path}.apogee_altitude",
                ProblemCode.ORDER,
                "El apogeo no puede estar por debajo del perigeo.",
            )
    if p.required(f"{path}.inclination", orbit.inclination, "la inclinación"):
        assert orbit.inclination is not None
        if orbit.inclination < 0:
            p.add(f"{path}.inclination", ProblemCode.MIN, "La inclinación no puede ser negativa.")
        elif orbit.inclination > math.pi:
            p.add(f"{path}.inclination", ProblemCode.MAX, "La inclinación no puede superar 180°.")


def _min_altitude(p: Problems, path: str, value_m: float, label: str) -> None:
    if value_m < MIN_ALTITUDE_M:
        p.add(
            path, ProblemCode.MIN, f"{label} tiene que ser de al menos {format_km(MIN_ALTITUDE_M)}."
        )


def _parallel_axes(a: Axis, b: Axis) -> bool:
    return a.value[1] == b.value[1]


def validate_attitude_modes(
    p: Problems, modes: list[AttitudeMode], path: str = "attitude_modes"
) -> None:
    """At least one mode, unique names, all four fields and two independent pairs."""
    if not modes:
        p.add(path, ProblemCode.REQUIRED, "Falta al menos un modo de actitud.")
    seen: set[str] = set()
    for i, mode in enumerate(modes):
        item = f"{path}[{i}]"
        p.unique_name(
            f"{item}.name",
            mode.name,
            seen,
            "el nombre del modo",
            "Ya hay un modo de actitud llamado",
        )
        p.required(f"{item}.primary_axis", mode.primary_axis, "el eje primario")
        p.required(f"{item}.primary_target", mode.primary_target, "la dirección primaria")
        p.required(f"{item}.secondary_axis", mode.secondary_axis, "el eje secundario")
        p.required(f"{item}.secondary_target", mode.secondary_target, "la dirección secundaria")
        if (
            mode.primary_axis is not None
            and mode.secondary_axis is not None
            and _parallel_axes(mode.primary_axis, mode.secondary_axis)
        ):
            p.add(
                f"{item}.secondary_axis",
                ProblemCode.PARALLEL,
                "El eje secundario no puede ser paralelo al primario.",
            )
        if (
            mode.primary_target is not None
            and mode.secondary_target is not None
            and (
                mode.primary_target is mode.secondary_target
                or frozenset({mode.primary_target, mode.secondary_target}) in _OPPOSITE_TARGETS
            )
        ):
            p.add(
                f"{item}.secondary_target",
                ProblemCode.PARALLEL,
                "La dirección secundaria no puede ser la misma ni la opuesta a la primaria.",
            )
