/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/catalog": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Catalog
     * @description Stage types in catalog order (class, required context types, implemented), phases and
     *     templates.
     */
    get: operations["get_catalog"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/catalog/stages/{stage}/artifact-schema": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Artifact Schema
     * @description JSON Schema of the artifact of a form stage (e.g. mission), with the SI unit and display
     *     unit of each physical field (`x-unit`, `x-display-unit`) and the other `x-` hints used to
     *     build the form. 422 `stage_not_implemented` for stages without a form.
     */
    get: operations["get_artifact_schema"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Stream Events
     * @description Server-Sent Events: one ``ProjectEvent`` per change of the workspace, whoever caused it.
     *
     *     The SSE event name is the event ``type``. The first event is ``connected`` with the current
     *     revision. Clients refetch the session when they receive an event.
     */
    get: operations["stream_events"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health
     * @description Liveness probe. No domain logic.
     */
    get: operations["health"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/project/branch-targets": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Branch Targets
     * @description Cells onto which a template or stage can be dropped to branch. Pass exactly one.
     */
    get: operations["list_branch_targets"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/project/cells/{cell_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Delete Cell
     * @description Delete a cell and its links (an emptied system is deleted). Requires a justification.
     */
    delete: operations["delete_cell"];
    options?: never;
    head?: never;
    /** Rename Cell */
    patch: operations["rename_cell"];
    trace?: never;
  };
  "/project/cells/{cell_id}/artifact": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Cell Artifact
     * @description The applied artifact of a form cell (mission) with its problems, per-field provenance,
     *     status and context. 422 `stage_not_implemented` for other stages.
     */
    get: operations["get_cell_artifact"];
    /**
     * Apply Cell Artifact
     * @description Replace the cell's artifact with the draft in one change of the history (one undo).
     *
     *     Requires a justification. Problems are allowed: the cell is then failed. Only the fields
     *     that changed get new provenance; everything downstream becomes outdated if the content
     *     changed. `change` is null if the content is the same as the applied one.
     */
    put: operations["apply_cell_artifact"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/project/cells/{cell_id}/artifact/validate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Validate Cell Artifact
     * @description Dry run: the problems of a draft. Changes nothing (no history, no status).
     */
    post: operations["validate_cell_artifact"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/project/cells/{cell_id}/branch": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Branch Cell
     * @description Create a new system (template or stage) and link this cell to its first cell that
     *     accepts it.
     */
    post: operations["branch_cell"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/project/cells/{cell_id}/branch-options": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Branch Options
     * @description Templates and stages that can be branched from this cell.
     */
    get: operations["list_branch_options"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/project/cells/{cell_id}/context": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Cell Context
     * @description Resolved context of a cell: the cell that provides each upstream stage type, and the
     *     required types that are missing (the cell cannot run until they are linked).
     */
    get: operations["get_cell_context"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/project/cells/{cell_id}/link-targets": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Link Targets
     * @description Cells this cell could feed with a new link right now.
     */
    get: operations["list_link_targets"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/project/clipboard/copy": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Copy To Clipboard
     * @description Snapshot systems and cells as a versioned fragment. Changes nothing in the project.
     */
    post: operations["copy_to_clipboard"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/project/clipboard/paste": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Paste From Clipboard
     * @description Create a fragment's systems and cells with new ids and its internal links.
     *
     *     One change in the history (one undo reverts it). Links to cells outside the fragment are
     *     not copied; pasted cells are never run.
     */
    post: operations["paste_from_clipboard"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/project/close": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Close Project
     * @description Close the project. Fails with ``unsaved_changes`` unless discarding.
     */
    post: operations["close_project"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/project/history": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get History
     * @description Every change of the project, oldest first, with author and justification.
     */
    get: operations["get_history"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/project/links": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Link Cells
     * @description Link two cells: the target gets the source's whole context (ADR 0016). A second parent
     *     is only valid if the contexts share no stage type (union).
     */
    post: operations["link_cells"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/project/links/{link_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Unlink Cells
     * @description Remove a link; its target and everything downstream become outdated.
     */
    delete: operations["unlink_cells"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/project/new": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * New Project
     * @description Start an empty, unsaved project. Fails with ``unsaved_changes`` unless discarding.
     */
    post: operations["new_project"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/project/open": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Open Project
     * @description Open a .hestia file. Fails with ``project_locked`` (423) if another instance has it.
     */
    post: operations["open_project"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/project/redo": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Redo
     * @description Redo the last undone change.
     */
    post: operations["redo"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/project/save": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Save Project
     * @description Save to the current file. Fails with ``no_path`` if it was never saved.
     */
    post: operations["save_project"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/project/save-as": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Save Project As
     * @description Save to a new file and keep working on it.
     */
    post: operations["save_project_as"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/project/systems": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create System
     * @description Create a system from a phase template (cells already linked) or with one cell.
     */
    post: operations["create_system"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/project/systems/{system_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Delete System
     * @description Delete a system, its cells and their links. Requires a justification.
     */
    delete: operations["delete_system"];
    options?: never;
    head?: never;
    /** Rename System */
    patch: operations["rename_system"];
    trace?: never;
  };
  "/project/systems/{system_id}/cells": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Add Cell
     * @description Add a cell to a system; it is linked to the cells of that system that complete its
     *     context (as target) or whose context it completes (as source).
     */
    post: operations["add_cell"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/project/systems/{system_id}/duplicate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Duplicate System
     * @description Copy a system with its cells, internal links and incoming links.
     */
    post: operations["duplicate_system"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/project/systems/{system_id}/move": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Move System
     * @description Move a system on the canvas.
     */
    post: operations["move_system"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/project/undo": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Undo
     * @description Undo the last change of this session (recorded in the history as well).
     */
    post: operations["undo"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/recents": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Recent Projects
     * @description Recently opened projects, newest first. ``exists`` is false for moved or deleted files.
     */
    get: operations["list_recent_projects"];
    put?: never;
    post?: never;
    /**
     * Remove Recent Project
     * @description Forget a recent project (the file is not touched).
     */
    delete: operations["remove_recent_project"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/session": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Session
     * @description The open project (schematic and file state), or null if none is open.
     */
    get: operations["get_session"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * ActorKind
     * @enum {string}
     */
    ActorKind: "human" | "agent";
    /** AddCellRequest */
    AddCellRequest: {
      /**
       * Justification
       * @description Why the change is made. Stored in the history with the author. Required (non-empty) for deletions and unlinking.
       */
      justification: string;
      /** Name */
      name?: string | null;
      stage: components["schemas"]["StageType"];
    };
    /**
     * ApiError
     * @description Error body. ``code`` is stable (e.g. ``project_locked``); ``message`` is for people.
     */
    ApiError: {
      /** Code */
      code: string;
      /** Details */
      details: {
        [key: string]: unknown;
      };
      /** Message */
      message: string;
    };
    /**
     * ApplyArtifactRequest
     * @description Replace the cell's artifact with the draft. The justification is required.
     */
    ApplyArtifactRequest: {
      artifact: components["schemas"]["MissionArtifact"];
      /**
       * Justification
       * @description Why the change is made. Stored in the history with the author. Required (non-empty) for deletions and unlinking.
       */
      justification: string;
    };
    /** ApplyArtifactResult */
    ApplyArtifactResult: {
      cell: components["schemas"]["CellArtifact"];
      change: components["schemas"]["Change"] | null;
      view: components["schemas"]["ProjectView"];
    };
    /**
     * ArtifactDraft
     * @description A draft of a form artifact, possibly incomplete. Its stage must match the cell's.
     */
    ArtifactDraft: {
      artifact: components["schemas"]["MissionArtifact"];
    };
    /**
     * AttitudeMode
     * @description Attitude from two body axis → direction pairs: the primary holds exactly, the secondary
     *     sets the rotation about the primary.
     */
    AttitudeMode: {
      /**
       * Id
       * @description Generated by the backend when applied. Immutable.
       */
      id?: string | null;
      /** Nombre */
      name?: string | null;
      /** Eje primario */
      primary_axis?: components["schemas"]["Axis"] | null;
      /** Dirección primaria */
      primary_target?: components["schemas"]["Target"] | null;
      /** Eje secundario */
      secondary_axis?: components["schemas"]["Axis"] | null;
      /** Dirección secundaria */
      secondary_target?: components["schemas"]["Target"] | null;
    };
    /**
     * Author
     * @description Who made a change. Humans and agents are shown the same way in the UI.
     */
    Author: {
      kind: components["schemas"]["ActorKind"];
      /** Name */
      name: string;
    };
    /**
     * Axis
     * @enum {string}
     */
    Axis: "+X" | "-X" | "+Y" | "-Y" | "+Z" | "-Z";
    /**
     * Blueprint
     * @description What to create: a template (whole phase) or a single stage. Exactly one is set.
     */
    Blueprint: {
      stage: components["schemas"]["StageType"] | null;
      template: components["schemas"]["TemplateId"] | null;
    };
    /**
     * BranchRequest
     * @description Create a system from a template or stage, fed by the cell in the path.
     */
    BranchRequest: {
      /**
       * Justification
       * @description Why the change is made. Stored in the history with the author. Required (non-empty) for deletions and unlinking.
       */
      justification: string;
      /** Name */
      name?: string | null;
      /** @description Canvas position. Placed automatically when omitted. */
      position?: components["schemas"]["Position"] | null;
      stage?: components["schemas"]["StageType"] | null;
      template?: components["schemas"]["TemplateId"] | null;
    };
    /** Catalog */
    Catalog: {
      /** Phases */
      phases: components["schemas"]["PhaseInfo"][];
      /** Stages */
      stages: components["schemas"]["StageInfo"][];
      /** Templates */
      templates: components["schemas"]["TemplateInfo"][];
    };
    /**
     * Cell
     * @description An instance of a stage type inside a system.
     */
    Cell: {
      form: components["schemas"]["FormState"] | null;
      /** Id */
      id: string;
      /** Name */
      name: string;
      provenance: components["schemas"]["Provenance"] | null;
      stage: components["schemas"]["StageType"];
      /** @default never_run */
      status: components["schemas"]["CellStatus"];
      /** System Id */
      system_id: string;
    };
    /**
     * CellArtifact
     * @description The artifact of a form cell as applied, with everything needed to edit it.
     */
    CellArtifact: {
      /** Applied */
      applied: boolean;
      artifact: components["schemas"]["MissionArtifact"];
      /** Cell Id */
      cell_id: string;
      context: components["schemas"]["CellContext"];
      /** Problems */
      problems: components["schemas"]["Problem"][];
      /** Provenance */
      provenance: {
        [key: string]: components["schemas"]["FieldProvenance"];
      };
      stage: components["schemas"]["StageType"];
      status: components["schemas"]["CellStatus"];
    };
    /**
     * CellContext
     * @description Resolved context of a cell: every cell upstream of it, by stage type.
     */
    CellContext: {
      /** Cell Id */
      cell_id: string;
      /** Entries */
      entries: components["schemas"]["ContextEntry"][];
      /** Missing */
      missing: components["schemas"]["StageType"][];
      stage: components["schemas"]["StageType"];
    };
    /** CellIds */
    CellIds: {
      /** Cell Ids */
      cell_ids: string[];
    };
    /**
     * CellStatus
     * @enum {string}
     */
    CellStatus: "up_to_date" | "outdated" | "failed" | "never_run";
    /**
     * Change
     * @description One entry of the project history.
     */
    Change: {
      author: components["schemas"]["Author"];
      /** Created Ids */
      created_ids: string[];
      /** Id */
      id: string;
      /** Justification */
      justification: string;
      operation: components["schemas"]["Operation"];
      /** Outdated Cell Ids */
      outdated_cell_ids: string[];
      /** Reverts */
      reverts: string | null;
      /** Seq */
      seq: number;
      /** Summary */
      summary: string;
      /**
       * Timestamp
       * Format: date-time
       */
      timestamp: string;
    };
    /** CloseProjectRequest */
    CloseProjectRequest: {
      /**
       * Discard Unsaved
       * @default false
       */
      discard_unsaved: boolean;
    };
    /**
     * ContextEntry
     * @description A stage type in the context of a cell and the cell that provides it.
     */
    ContextEntry: {
      /** Cell Id */
      cell_id: string;
      /** Cell Name */
      cell_name: string;
      stage: components["schemas"]["StageType"];
      /** System Id */
      system_id: string;
    };
    /**
     * CopyRequest
     * @description What to copy: whole systems and/or loose cells.
     */
    CopyRequest: {
      /** Cell Ids */
      cell_ids?: string[];
      /** System Ids */
      system_ids?: string[];
    };
    /**
     * CreateSystemRequest
     * @description Create a system from a template (``template``) or with a single cell (``stage``).
     */
    CreateSystemRequest: {
      /**
       * Justification
       * @description Why the change is made. Stored in the history with the author. Required (non-empty) for deletions and unlinking.
       */
      justification: string;
      /** Name */
      name?: string | null;
      /** @description Canvas position. Placed automatically when omitted. */
      position?: components["schemas"]["Position"] | null;
      stage?: components["schemas"]["StageType"] | null;
      template?: components["schemas"]["TemplateId"] | null;
    };
    /** Criteria */
    Criteria: {
      /**
       * Margen de aceptación
       * @description ΔT.
       * @default 5
       */
      acceptance_margin: number | null;
      /**
       * Potencia para heaters
       * @description Promedio orbital disponible.
       */
      heater_power_budget?: number | null;
      /**
       * Margen de calificación
       * @description Sobre el de aceptación (ΔT).
       * @default 5
       */
      qualification_margin: number | null;
      /**
       * Caras de radiador
       * @description Caras donde se permite ubicar radiadores. Vacío: sin restricción.
       */
      radiator_faces?: components["schemas"]["Face"][];
      /** Masa para el TCS */
      tcs_mass_budget?: number | null;
      /**
       * Margen de incertidumbre
       * @description Incertidumbre de las predicciones (ΔT).
       * @default 10
       */
      uncertainty_margin: number | null;
    };
    /**
     * DocumentState
     * @description File-level state of the open project.
     */
    DocumentState: {
      /** Can Redo */
      can_redo: boolean;
      /** Can Undo */
      can_undo: boolean;
      /** Dirty */
      dirty: boolean;
      /** File Name */
      file_name: string | null;
      /** Path */
      path: string | null;
      /** Redo Label */
      redo_label: string | null;
      /** Redo Summary */
      redo_summary: string | null;
      /** Revision */
      revision: number;
      /** Undo Label */
      undo_label: string | null;
      /** Undo Summary */
      undo_summary: string | null;
    };
    /** DuplicateSystemRequest */
    DuplicateSystemRequest: {
      /**
       * Justification
       * @description Why the change is made. Stored in the history with the author. Required (non-empty) for deletions and unlinking.
       */
      justification: string;
      position?: components["schemas"]["Position"] | null;
    };
    /** Envelope */
    Envelope: {
      /**
       * Masa
       * @description Masa total del satélite en órbita, al inicio de vida.
       */
      mass?: number | null;
      /** Dimensión X */
      size_x?: number | null;
      /** Dimensión Y */
      size_y?: number | null;
      /** Dimensión Z */
      size_z?: number | null;
    };
    /**
     * EventType
     * @enum {string}
     */
    EventType:
      | "connected"
      | "project_created"
      | "project_opened"
      | "project_saved"
      | "project_closed"
      | "project_changed";
    /**
     * Face
     * @enum {string}
     */
    Face: "+X" | "-X" | "+Y" | "-Y" | "+Z" | "-Z";
    /** FieldProvenance */
    FieldProvenance: {
      /** Change Id */
      change_id: string | null;
      source: components["schemas"]["FieldSource"];
    };
    /**
     * FieldSource
     * @description Where the value of a form field comes from (ADR 0017).
     * @enum {string}
     */
    FieldSource: "entered" | "imported" | "default";
    /**
     * FormState
     * @description Artifact of a form stage as applied, with its problems and per-field provenance.
     */
    FormState: {
      /** Artifact */
      artifact: {
        [key: string]: unknown;
      };
      /** Problems */
      problems: components["schemas"]["Problem"][];
      /** Provenance */
      provenance: {
        [key: string]: components["schemas"]["FieldProvenance"];
      };
    };
    /** Fragment */
    "Fragment-Input": {
      /**
       * Kind
       * @default hestia.fragment
       * @constant
       */
      kind: "hestia.fragment";
      /** Links */
      links?: components["schemas"]["FragmentLink"][];
      /**
       * Schema Version
       * @default 2
       */
      schema_version: number;
      /** Source Project Id */
      source_project_id: string;
      /** Systems */
      systems?: components["schemas"]["FragmentSystem-Input"][];
    };
    /** Fragment */
    "Fragment-Output": {
      /**
       * Kind
       * @default hestia.fragment
       * @constant
       */
      kind: "hestia.fragment";
      /** Links */
      links: components["schemas"]["FragmentLink"][];
      /**
       * Schema Version
       * @default 2
       */
      schema_version: number;
      /** Source Project Id */
      source_project_id: string;
      /** Systems */
      systems: components["schemas"]["FragmentSystem-Output"][];
    };
    /** FragmentCell */
    "FragmentCell-Input": {
      form?: components["schemas"]["FragmentForm-Input"] | null;
      /** Id */
      id: string;
      /** Name */
      name: string;
      stage: components["schemas"]["StageType"];
    };
    /** FragmentCell */
    "FragmentCell-Output": {
      form: components["schemas"]["FragmentForm-Output"] | null;
      /** Id */
      id: string;
      /** Name */
      name: string;
      stage: components["schemas"]["StageType"];
    };
    /**
     * FragmentForm
     * @description Artifact of a form cell (ADR 0017).
     */
    "FragmentForm-Input": {
      /** Applied */
      applied: boolean;
      /** Artifact */
      artifact: {
        [key: string]: unknown;
      };
      /** Sources */
      sources?: {
        [key: string]: components["schemas"]["FieldSource"];
      };
    };
    /**
     * FragmentForm
     * @description Artifact of a form cell (ADR 0017).
     */
    "FragmentForm-Output": {
      /** Applied */
      applied: boolean;
      /** Artifact */
      artifact: {
        [key: string]: unknown;
      };
      /** Sources */
      sources: {
        [key: string]: components["schemas"]["FieldSource"];
      };
    };
    /** FragmentLink */
    FragmentLink: {
      /** Source Cell Id */
      source_cell_id: string;
      /** Target Cell Id */
      target_cell_id: string;
    };
    /**
     * FragmentSystem
     * @description A system of the source project with the copied cells, in display order.
     *
     *     ``whole`` is false when only some of its cells were copied: pasting then adds those cells
     *     to the target system if one is given, or creates a system with this name.
     */
    "FragmentSystem-Input": {
      /** Cells */
      cells: components["schemas"]["FragmentCell-Input"][];
      /** Name */
      name: string;
      position: components["schemas"]["Position"];
      /** Whole */
      whole: boolean;
    };
    /**
     * FragmentSystem
     * @description A system of the source project with the copied cells, in display order.
     *
     *     ``whole`` is false when only some of its cells were copied: pasting then adds those cells
     *     to the target system if one is given, or creates a system with this name.
     */
    "FragmentSystem-Output": {
      /** Cells */
      cells: components["schemas"]["FragmentCell-Output"][];
      /** Name */
      name: string;
      position: components["schemas"]["Position"];
      /** Whole */
      whole: boolean;
    };
    /** General */
    General: {
      /**
       * Descripción
       * @description Objetivo y notas generales.
       */
      description?: string | null;
      /**
       * Vida útil de diseño
       * @description Define el fin de vida (degradación de recubrimientos, EOL).
       */
      design_life?: number | null;
      /**
       * Fecha de lanzamiento
       * @description Define las estaciones que recorre la misión (flujo solar, historia de β).
       */
      launch_date?: string | null;
    };
    /**
     * Link
     * @description Passes the context of ``source_cell_id`` (the cell and everything upstream of it) on to
     *     ``target_cell_id`` (ADR 0016).
     */
    Link: {
      /** Id */
      id: string;
      /** Source Cell Id */
      source_cell_id: string;
      /** Target Cell Id */
      target_cell_id: string;
    };
    /** LinkRequest */
    LinkRequest: {
      /**
       * Justification
       * @description Why the change is made. Stored in the history with the author. Required (non-empty) for deletions and unlinking.
       */
      justification: string;
      /** Source Cell Id */
      source_cell_id: string;
      /** Target Cell Id */
      target_cell_id: string;
    };
    /**
     * MissionArtifact
     * @description Artifact of the mission stage: orbit, attitude, envelope and criteria.
     */
    MissionArtifact: {
      /** Modos de actitud */
      attitude_modes?: components["schemas"]["AttitudeMode"][];
      /** Criterios y restricciones */
      criteria?: components["schemas"]["Criteria"];
      /** Envolvente */
      envelope?: components["schemas"]["Envelope"];
      general?: components["schemas"]["General"];
      /** Órbita */
      orbit?: components["schemas"]["Orbit"];
      /**
       * Schema Version
       * @default 1
       */
      schema_version: number;
    };
    /** MoveSystemRequest */
    MoveSystemRequest: {
      /**
       * Justification
       * @description Why the change is made. Stored in the history with the author. Required (non-empty) for deletions and unlinking.
       */
      justification: string;
      position: components["schemas"]["Position"];
    };
    /** MutationResult */
    MutationResult: {
      change: components["schemas"]["Change"];
      view: components["schemas"]["ProjectView"];
    };
    /** NewProjectRequest */
    NewProjectRequest: {
      /**
       * Discard Unsaved
       * @description Replace an open project even if it has unsaved changes.
       * @default false
       */
      discard_unsaved: boolean;
      /** Name */
      name?: string | null;
    };
    /** OpenProjectRequest */
    OpenProjectRequest: {
      /**
       * Discard Unsaved
       * @default false
       */
      discard_unsaved: boolean;
      /**
       * Force
       * @description Take over the file even if another instance holds its lock.
       * @default false
       */
      force: boolean;
      /**
       * Path
       * @description Absolute path of the .hestia file.
       */
      path: string;
    };
    /**
     * Operation
     * @enum {string}
     */
    Operation:
      | "create_system"
      | "add_cell"
      | "link"
      | "unlink"
      | "branch"
      | "rename_system"
      | "rename_cell"
      | "move_system"
      | "duplicate_system"
      | "delete_system"
      | "delete_cell"
      | "paste"
      | "apply_artifact"
      | "undo"
      | "redo";
    /** Orbit */
    Orbit: {
      /**
       * Altitud
       * @description Órbita circular.
       */
      altitude?: number | null;
      /**
       * Altitud del apogeo
       * @description Vacío: órbita circular (igual al perigeo).
       */
      apogee_altitude?: number | null;
      /** Inclinación */
      inclination?: number | null;
      /**
       * LTAN
       * @description Hora local (solar media) del nodo ascendente, HH:MM.
       */
      ltan?: string | null;
      /** Altitud del perigeo */
      perigee_altitude?: number | null;
      /**
       * Tipo de órbita
       * @default sso
       */
      type: components["schemas"]["OrbitType"] | null;
    };
    /**
     * OrbitType
     * @enum {string}
     */
    OrbitType: "sso" | "keplerian" | "geo";
    /** PasteRequest */
    PasteRequest: {
      /** @description A fragment returned by copy (any project). */
      fragment: components["schemas"]["Fragment-Input"];
      /**
       * Justification
       * @description Why the change is made. Stored in the history with the author. Required (non-empty) for deletions and unlinking.
       */
      justification: string;
      /** @description Canvas position of the fragment's top-left system. When omitted, systems are shifted from the originals. */
      position?: components["schemas"]["Position"] | null;
      /**
       * Target System Id
       * @description System that receives loose cells. When omitted they get a new system.
       */
      target_system_id?: string | null;
    };
    /**
     * Phase
     * @enum {string}
     */
    Phase: "phase_0" | "phase_1";
    /** PhaseInfo */
    PhaseInfo: {
      /** Name */
      name: string;
      phase: components["schemas"]["Phase"];
      template: components["schemas"]["TemplateId"];
    };
    /**
     * Position
     * @description Canvas position of a system, in schematic units (px at zoom 1).
     */
    Position: {
      /** X */
      x: number;
      /** Y */
      y: number;
    };
    /**
     * Problem
     * @description A validation problem of a form artifact. Validating never produces values.
     */
    Problem: {
      code: components["schemas"]["ProblemCode"];
      /** Message */
      message: string;
      /** Path */
      path: string;
    };
    /**
     * ProblemCode
     * @description Stable codes of validation problems (``docs/etapas/*.md``).
     * @enum {string}
     */
    ProblemCode:
      | "required"
      | "min"
      | "max"
      | "order"
      | "not_allowed"
      | "format"
      | "sso_altitude"
      | "parallel"
      | "duplicate_name"
      | "duplicate";
    /** Project */
    Project: {
      /** Cells */
      cells: components["schemas"]["Cell"][];
      /** Id */
      id: string;
      /** Links */
      links: components["schemas"]["Link"][];
      /** Name */
      name: string;
      /**
       * Schema Version
       * @default 3
       */
      schema_version: number;
      /** Systems */
      systems: components["schemas"]["System"][];
    };
    /**
     * ProjectEvent
     * @description Notification for real-time clients. ``change`` is set for ``project_changed``.
     */
    ProjectEvent: {
      change: components["schemas"]["Change"] | null;
      /** Message */
      message: string;
      /** Path */
      path: string | null;
      /** Revision */
      revision: number | null;
      /**
       * Timestamp
       * Format: date-time
       */
      timestamp: string;
      type: components["schemas"]["EventType"];
      /** Warnings */
      warnings: string[];
    };
    /** ProjectView */
    ProjectView: {
      document: components["schemas"]["DocumentState"];
      /** Missing */
      missing: {
        [key: string]: components["schemas"]["StageType"][];
      };
      project: components["schemas"]["Project"];
    };
    /**
     * Provenance
     * @description What produced a cell's current outputs. Empty until stages can run.
     */
    Provenance: {
      /** Code Version */
      code_version: string;
      /** Input Cell Ids */
      input_cell_ids: string[];
      /**
       * Produced At
       * Format: date-time
       */
      produced_at: string;
    };
    /** RecentProject */
    RecentProject: {
      /** Exists */
      exists: boolean;
      /** Name */
      name: string;
      /**
       * Opened At
       * Format: date-time
       */
      opened_at: string;
      /** Path */
      path: string;
    };
    /** RemoveRecentRequest */
    RemoveRecentRequest: {
      /** Path */
      path: string;
    };
    /** RenameRequest */
    RenameRequest: {
      /**
       * Justification
       * @description Why the change is made. Stored in the history with the author. Required (non-empty) for deletions and unlinking.
       */
      justification: string;
      /** Name */
      name: string;
    };
    /** SaveAsRequest */
    SaveAsRequest: {
      /**
       * Path
       * @description Target path. The .hestia extension is added if missing.
       */
      path: string;
    };
    /**
     * Session
     * @description What this API instance has open. ``project`` is null when nothing is open.
     */
    Session: {
      project: components["schemas"]["ProjectView"] | null;
    };
    /** StageInfo */
    StageInfo: {
      /** Implemented */
      implemented: boolean;
      kind: components["schemas"]["StageKind"];
      /** Name */
      name: string;
      /** Number */
      number: string;
      /** Order */
      order: number;
      phase: components["schemas"]["Phase"];
      /** Requires */
      requires: components["schemas"]["StageType"][];
      /** Root */
      root: boolean;
      stage: components["schemas"]["StageType"];
    };
    /**
     * StageKind
     * @description How a stage produces its artifact.
     * @enum {string}
     */
    StageKind: "form" | "computation" | "collector";
    /**
     * StageType
     * @description Stage types in catalog order (0.1 < 0.2 < … < 0.5 < 1.1 < … < 1.6).
     * @enum {string}
     */
    StageType:
      | "mission"
      | "environment"
      | "equipment"
      | "global_balance"
      | "tcs_concept"
      | "discretization"
      | "couplings"
      | "load_cases"
      | "solution"
      | "margins"
      | "sensitivity";
    /**
     * System
     * @description Named group of cells. ``cell_ids`` keeps display order.
     */
    System: {
      /** Cell Ids */
      cell_ids: string[];
      /** Id */
      id: string;
      /** Name */
      name: string;
      position: components["schemas"]["Position"];
    };
    /**
     * Target
     * @enum {string}
     */
    Target:
      | "nadir"
      | "zenith"
      | "sun"
      | "velocity"
      | "anti_velocity"
      | "orbit_normal"
      | "anti_orbit_normal";
    /**
     * TemplateId
     * @enum {string}
     */
    TemplateId: "phase_0" | "phase_1";
    /** TemplateInfo */
    TemplateInfo: {
      /** Description */
      description: string;
      id: components["schemas"]["TemplateId"];
      /** Links */
      links: components["schemas"]["TemplateLink"][];
      /** Name */
      name: string;
      phase: components["schemas"]["Phase"];
      /** Stages */
      stages: components["schemas"]["StageType"][];
    };
    /** TemplateLink */
    TemplateLink: {
      source: components["schemas"]["StageType"];
      target: components["schemas"]["StageType"];
    };
    /** ValidationResult */
    ValidationResult: {
      /** Problems */
      problems: components["schemas"]["Problem"][];
    };
    /** WriteRequest */
    WriteRequest: {
      /**
       * Justification
       * @description Why the change is made. Stored in the history with the author. Required (non-empty) for deletions and unlinking.
       */
      justification: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  get_catalog: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Catalog"];
        };
      };
    };
  };
  get_artifact_schema: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        stage: components["schemas"]["StageType"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Locked */
      423: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  stream_events: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/event-stream": unknown;
        };
      };
    };
  };
  health: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  list_branch_targets: {
    parameters: {
      query?: {
        template?: components["schemas"]["TemplateId"] | null;
        stage?: components["schemas"]["StageType"] | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CellIds"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Locked */
      423: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  delete_cell: {
    parameters: {
      query?: never;
      header?: {
        /** @description Author name. Defaults to the OS user running the API. */
        "x-hestia-actor"?: string | null;
        /** @description `human` (UI) or `agent` (MCP and other agents). */
        "x-hestia-actor-kind"?: components["schemas"]["ActorKind"];
      };
      path: {
        cell_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["WriteRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MutationResult"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Locked */
      423: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  rename_cell: {
    parameters: {
      query?: never;
      header?: {
        /** @description Author name. Defaults to the OS user running the API. */
        "x-hestia-actor"?: string | null;
        /** @description `human` (UI) or `agent` (MCP and other agents). */
        "x-hestia-actor-kind"?: components["schemas"]["ActorKind"];
      };
      path: {
        cell_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RenameRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MutationResult"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Locked */
      423: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  get_cell_artifact: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        cell_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CellArtifact"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Locked */
      423: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  apply_cell_artifact: {
    parameters: {
      query?: never;
      header?: {
        /** @description Author name. Defaults to the OS user running the API. */
        "x-hestia-actor"?: string | null;
        /** @description `human` (UI) or `agent` (MCP and other agents). */
        "x-hestia-actor-kind"?: components["schemas"]["ActorKind"];
      };
      path: {
        cell_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ApplyArtifactRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplyArtifactResult"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Locked */
      423: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  validate_cell_artifact: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        cell_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ArtifactDraft"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ValidationResult"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Locked */
      423: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  branch_cell: {
    parameters: {
      query?: never;
      header?: {
        /** @description Author name. Defaults to the OS user running the API. */
        "x-hestia-actor"?: string | null;
        /** @description `human` (UI) or `agent` (MCP and other agents). */
        "x-hestia-actor-kind"?: components["schemas"]["ActorKind"];
      };
      path: {
        cell_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BranchRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MutationResult"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Locked */
      423: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  list_branch_options: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        cell_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Blueprint"][];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Locked */
      423: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  get_cell_context: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        cell_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CellContext"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Locked */
      423: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  list_link_targets: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        cell_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CellIds"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Locked */
      423: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  copy_to_clipboard: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CopyRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Fragment-Output"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Locked */
      423: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  paste_from_clipboard: {
    parameters: {
      query?: never;
      header?: {
        /** @description Author name. Defaults to the OS user running the API. */
        "x-hestia-actor"?: string | null;
        /** @description `human` (UI) or `agent` (MCP and other agents). */
        "x-hestia-actor-kind"?: components["schemas"]["ActorKind"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PasteRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MutationResult"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Locked */
      423: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  close_project: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CloseProjectRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Session"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Locked */
      423: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  get_history: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Change"][];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Locked */
      423: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  link_cells: {
    parameters: {
      query?: never;
      header?: {
        /** @description Author name. Defaults to the OS user running the API. */
        "x-hestia-actor"?: string | null;
        /** @description `human` (UI) or `agent` (MCP and other agents). */
        "x-hestia-actor-kind"?: components["schemas"]["ActorKind"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LinkRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MutationResult"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Locked */
      423: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  unlink_cells: {
    parameters: {
      query?: never;
      header?: {
        /** @description Author name. Defaults to the OS user running the API. */
        "x-hestia-actor"?: string | null;
        /** @description `human` (UI) or `agent` (MCP and other agents). */
        "x-hestia-actor-kind"?: components["schemas"]["ActorKind"];
      };
      path: {
        link_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["WriteRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MutationResult"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Locked */
      423: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  new_project: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["NewProjectRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectView"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Locked */
      423: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  open_project: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["OpenProjectRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectView"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Locked */
      423: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  redo: {
    parameters: {
      query?: never;
      header?: {
        /** @description Author name. Defaults to the OS user running the API. */
        "x-hestia-actor"?: string | null;
        /** @description `human` (UI) or `agent` (MCP and other agents). */
        "x-hestia-actor-kind"?: components["schemas"]["ActorKind"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["WriteRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MutationResult"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Locked */
      423: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  save_project: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectView"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Locked */
      423: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  save_project_as: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SaveAsRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectView"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Locked */
      423: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  create_system: {
    parameters: {
      query?: never;
      header?: {
        /** @description Author name. Defaults to the OS user running the API. */
        "x-hestia-actor"?: string | null;
        /** @description `human` (UI) or `agent` (MCP and other agents). */
        "x-hestia-actor-kind"?: components["schemas"]["ActorKind"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateSystemRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MutationResult"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Locked */
      423: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  delete_system: {
    parameters: {
      query?: never;
      header?: {
        /** @description Author name. Defaults to the OS user running the API. */
        "x-hestia-actor"?: string | null;
        /** @description `human` (UI) or `agent` (MCP and other agents). */
        "x-hestia-actor-kind"?: components["schemas"]["ActorKind"];
      };
      path: {
        system_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["WriteRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MutationResult"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Locked */
      423: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  rename_system: {
    parameters: {
      query?: never;
      header?: {
        /** @description Author name. Defaults to the OS user running the API. */
        "x-hestia-actor"?: string | null;
        /** @description `human` (UI) or `agent` (MCP and other agents). */
        "x-hestia-actor-kind"?: components["schemas"]["ActorKind"];
      };
      path: {
        system_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RenameRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MutationResult"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Locked */
      423: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  add_cell: {
    parameters: {
      query?: never;
      header?: {
        /** @description Author name. Defaults to the OS user running the API. */
        "x-hestia-actor"?: string | null;
        /** @description `human` (UI) or `agent` (MCP and other agents). */
        "x-hestia-actor-kind"?: components["schemas"]["ActorKind"];
      };
      path: {
        system_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AddCellRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MutationResult"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Locked */
      423: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  duplicate_system: {
    parameters: {
      query?: never;
      header?: {
        /** @description Author name. Defaults to the OS user running the API. */
        "x-hestia-actor"?: string | null;
        /** @description `human` (UI) or `agent` (MCP and other agents). */
        "x-hestia-actor-kind"?: components["schemas"]["ActorKind"];
      };
      path: {
        system_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DuplicateSystemRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MutationResult"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Locked */
      423: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  move_system: {
    parameters: {
      query?: never;
      header?: {
        /** @description Author name. Defaults to the OS user running the API. */
        "x-hestia-actor"?: string | null;
        /** @description `human` (UI) or `agent` (MCP and other agents). */
        "x-hestia-actor-kind"?: components["schemas"]["ActorKind"];
      };
      path: {
        system_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MoveSystemRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MutationResult"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Locked */
      423: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  undo: {
    parameters: {
      query?: never;
      header?: {
        /** @description Author name. Defaults to the OS user running the API. */
        "x-hestia-actor"?: string | null;
        /** @description `human` (UI) or `agent` (MCP and other agents). */
        "x-hestia-actor-kind"?: components["schemas"]["ActorKind"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["WriteRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MutationResult"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Locked */
      423: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  list_recent_projects: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RecentProject"][];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Locked */
      423: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  remove_recent_project: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RemoveRecentRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RecentProject"][];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Locked */
      423: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  get_session: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Session"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
      /** @description Locked */
      423: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiError"];
        };
      };
    };
  };
}
